// <auto-generated />
using System;
using HMO.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMO.Context.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230509130643_add_image")]
    partial class add_image
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMO.Repository.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("HMO.Repository.Entities.Vaccination", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date_vaccination")
                        .HasColumnType("datetime2");

                    b.Property<string>("identityid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("producerid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("identityid");

                    b.HasIndex("producerid");

                    b.ToTable("Vaccination");
                });

            modelBuilder.Entity("HMO.Repository.PersonalDetailes", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("cityid")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_ill")
                        .HasColumnType("datetime2");

                    b.Property<int>("house_number")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pelephon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("start_ill")
                        .HasColumnType("datetime2");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vaccination_number")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cityid");

                    b.ToTable("PersonalDetailes");
                });

            modelBuilder.Entity("HMO.Repository.Producer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Producer");
                });

            modelBuilder.Entity("HMO.Repository.Entities.Vaccination", b =>
                {
                    b.HasOne("HMO.Repository.PersonalDetailes", "identity")
                        .WithMany()
                        .HasForeignKey("identityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMO.Repository.Producer", "producer")
                        .WithMany()
                        .HasForeignKey("producerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("identity");

                    b.Navigation("producer");
                });

            modelBuilder.Entity("HMO.Repository.PersonalDetailes", b =>
                {
                    b.HasOne("HMO.Repository.City", "city")
                        .WithMany()
                        .HasForeignKey("cityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });
#pragma warning restore 612, 618
        }
    }
}
