//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ownedBy
    {
        public int id { get; set; }
        public int pokemon_id { get; set; }
        public int trainer_id { get; set; }
    
        public virtual pokemon_details pokemon_details { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
