//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokemon_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pokemon_details()
        {
            this.ownedBies = new HashSet<ownedBy>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ownedBy> ownedBies { get; set; }
    }
}
